spring.application.name=spring-note-rest-api

spring.datasource.url=jdbc:postgresql://localhost:5432/note_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

api.host.baseurl=http://localhost:8010/v2/check